name: Trunk-Based CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PYTHON_VERSION: '3.9'

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y tesseract-ocr poppler-utils libgl1-mesa-glx || true
        sudo apt-get install -y libgl1-mesa-dev libglib2.0-0 libsm6 libxext6 libxrender-dev libgomp1 || true
        
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install numpy==1.24.3
        pip install -r requirements.txt
        
    - name: Run comprehensive tests
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        REDIS_URL: redis://localhost:6379
        FLASK_ENV: testing
      run: |
        python run_tests.py --unit --integration
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: test_results/
        
    - name: Comment test results on PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          try {
            const summary = JSON.parse(fs.readFileSync('test_results/latest_test_summary.json', 'utf8'));
            const comment = `## 🧪 Test Results
            
            | Metric | Value | Status |
            |--------|-------|--------|
            | 🎯 Accuracy | ${(summary.accuracy_rate * 100).toFixed(1)}% | ${summary.accuracy_rate >= 0.8 ? '✅' : '❌'} |
            | ⚡ Avg Latency | ${summary.average_latency_ms.toFixed(0)}ms | ${summary.average_latency_ms <= 10000 ? '✅' : '❌'} |
            | 🟢 Availability | ${(summary.availability_rate * 100).toFixed(1)}% | ${summary.availability_rate >= 0.95 ? '✅' : '❌'} |
            | 💰 Total Cost | $${summary.total_cost_usd.toFixed(4)} | ℹ️ |
            | 🎫 Tokens Used | ${summary.total_tokens_used.toLocaleString()} | ℹ️ |
            
            **Overall Status:** ${summary.accuracy_rate >= 0.8 && summary.average_latency_ms <= 10000 && summary.availability_rate >= 0.95 ? '✅ PASSED' : '❌ FAILED'}
            `;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
          } catch (error) {
            console.log('Could not read test summary:', error);
          }
        
  docker-build:
    runs-on: ubuntu-latest
    needs: [test]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        load: true
        tags: document-classifier:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Test Docker image
      run: |
        docker run --rm -d --name test-container -p 5000:5000 \
          -e OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" \
          document-classifier:latest
        sleep 10
        # Check if container is still running (didn't crash)
        docker ps | grep test-container || exit 1
        echo "✅ Docker container started successfully"
        docker stop test-container

  deployment-ready:
    runs-on: ubuntu-latest
    needs: [docker-build]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v4
        
    - name: Deployment Ready Notification
      uses: actions/github-script@v6
      with:
        script: |
          const { owner, repo } = context.repo;
          github.rest.issues.createComment({
            owner,
            repo,
            issue_number: context.payload.head_commit?.id || 'latest',
            body: '✅ **Ready for Deployment!**\n\n🧪 All tests passed\n🐳 Docker build successful\n🚀 Ready to deploy to Railway\n\n**Manual Deployment:** Run `railway up` locally to deploy'
          }).catch(() => {
            console.log('Could not create comment, but tests passed');
          });

  performance-monitoring:
    runs-on: ubuntu-latest
    needs: [deployment-ready]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Run performance monitoring
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        echo "Performance monitoring skipped in CI - requires test files and production URL"
        
    - name: Upload performance results
      uses: actions/upload-artifact@v4
      with:
        name: performance-results
        path: test_results/
